/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.todo.model.impl;

import com.example.todo.model.Todo;
import com.example.todo.service.TodoLocalServiceUtil;

/**
 * The extended model base implementation for the Todo service. Represents a row in the &quot;TODO_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TodoImpl
 * @see Todo
 * @generated
 */
public abstract class TodoBaseImpl extends TodoModelImpl implements Todo {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a todo model instance should use the <code>Todo</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TodoLocalServiceUtil.addTodo(this);
		}
		else {
			TodoLocalServiceUtil.updateTodo(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-962525017